version: '3.9'

services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: learning_auth_rbac_db
